"""Embed firmware/FarmeLink/ui/index.html into src/web_ui.h (flash-resident string).

Run after editing the page:  python tools/embed_ui.py
tests/test_firmware_files.py fails if the header is out of date.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "firmware" / "FarmeLink" / "ui" / "index.html"
DST = ROOT / "firmware" / "FarmeLink" / "src" / "web_ui.h"


def render() -> str:
    html = SRC.read_text(encoding="utf-8")
    assert ")FARME\"" not in html
    return (
        "// web_ui.h - generated by tools/embed_ui.py from ui/index.html; do not edit.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        f"// {len(html.encode())} bytes, served at \"/\"\n"
        f"static const char WEB_UI[] PROGMEM = R\"FARME({html})FARME\";\n"
    )


if __name__ == "__main__":
    DST.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {DST.relative_to(ROOT)}")
